services:
  - type: web
    name: nasdaq100-webull-radar
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8080
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_USER_ID
        sync: false
